### ISSUE TITLE
Features list

### ISSUE THREAD

**Issue by oorjitchowdhary** [kyt-app/kyt-mobile#1]
To be implemented for the revised idea.

- [x] Passport number input according to countries
Add support for India and US passports.
- [x] Verify passport number using regex
- [x] Post registration details to KYT API
- [x] Camera intent for using Azure CV [#3]
- [x] Get text from photo using Azure CV OCR and post to KYT API [#4]
- [x] Post verified data to the KYT API to store on the database
- [x] Scan QR screen for the user which generates a QR code according to the user's current profile [#5]
